# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-24 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Producto', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Precio_Venta', models.IntegerField(max_length=5)),
                ('Precio_Compra', models.IntegerField(max_length=5)),
                ('Clave_Producto', models.CharField(max_length=6)),
                ('Existencias', models.IntegerField(max_length=5)),
                ('color', models.CharField(choices=[('O', 'Oro'), ('P', 'Plata'), ('B', 'Bronce'), ('R', 'Rosa'), ('T', 'Turco')], default='O', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('Nombre_Pila_Vendedor', models.CharField(max_length=10)),
                ('Apellido_Paterno_Vendedor', models.CharField(max_length=10)),
                ('Apellido_Materno_Vendedor', models.CharField(max_length=10)),
                ('Clave_Vendedor', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('num_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now=True)),
                ('cantidad', models.SmallIntegerField()),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.Producto')),
                ('Vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.Vendedor')),
            ],
        ),
    ]
