# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-24 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('Nombre_Pila_Vendedor', models.CharField(max_length=10)),
                ('Apellido_Paterno_Vendedor', models.CharField(max_length=10)),
                ('Apellido_Materno_Vendedor', models.CharField(max_length=10)),
                ('Correo', models.EmailField(max_length=254)),
                ('Contraseña', models.CharField(max_length=20)),
                ('Clave_Vendedor', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='material',
            field=models.CharField(choices=[('A', 'Acero'), ('O', 'Oro'), ('P', 'Plata'), ('C', 'Cobre'), ('B', 'Bisuteria')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Existencias',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Precio_Compra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Precio_Venta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(choices=[('O', 'Oro'), ('P', 'Plata'), ('B', 'Cobre'), ('R', 'Rosa'), ('T', 'Turco')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='venta',
            name='Vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.Comprador'),
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
