# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-24 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_auto_20180324_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='Vendedor',
            new_name='Comprador',
        ),
    ]
