# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-26 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_auto_20180324_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprador',
            name='Clave_Vendedor',
        ),
        migrations.RemoveField(
            model_name='comprador',
            name='Contraseña',
        ),
        migrations.AddField(
            model_name='comprador',
            name='Contra',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='Correo',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
